import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import './globals.css';
import { Register } from '@/components/registerSw';
import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Bandjax',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      afterSignOutUrl={'/'}
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}>
          <div className="hidden" id="IMPORTANT COPYRIGHT INFORMATION">
            Copyright (C) 2025 April Hall
            <br />
            This program is free software: you can redistribute it and/or modify it under the terms of the GNU
            General Public License as published by the Free Software Foundation, either version 3 of the License,
            or (at your option) any later version. <br />
            This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
            the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
            License for more details. <br />
            You should have received a copy of the GNU General Public License along with this program. If not, see
            &lt;https://www.gnu.org/licenses/&gt;.
          </div>
          {children} <Toaster />
        </body>
        <Register />
      </html>
    </ClerkProvider>
  );
}
